<a href="https://colab.research.google.com/github/bathicodes/Augmentic/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Initiate the notebook

In [ ]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



## Import PyTorch

In [ ]:
import torch

print(torch.__version__)

1.13.1+cu116


## Introduction to Tensors

### Creating tensor

#### **Scalar**

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# Check tensor's dimentions
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

#### **Vector**

In [ ]:
# Creatinf vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
# Check vector's dimentions
vector.ndim

1

In [ ]:
# Check vector's shape
vector.shape

torch.Size([2])

#### **MATRIX**

In [ ]:
# Creating a MATRIX
MATRIX = torch.tensor([[1, 2],
                       [3, 4]])

MATRIX

tensor([[1, 2],
        [3, 4]])

In [ ]:
# Check MATRIX's dimentions
MATRIX.ndim

2

In [ ]:
# Check MATRIX's shape
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Get the first element from MATRIX
MATRIX[0]

tensor([1, 2])

In [ ]:
# Get the second element from MATRIX
MATRIX[1]

tensor([3, 4])

#### **TENSOR**

In [ ]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
# Check TENSOR's dimentions
TENSOR.ndim

3

In [ ]:
# Check TENSOR's shape
TENSOR.shape

torch.Size([1, 3, 3])

# Random Tensors

Why random tensors? 

Most of the Neural Networks use random tensor in the learning state to initialized random values to the weights.

In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7055, 0.9354, 0.5277, 0.0369],
        [0.1835, 0.9050, 0.1210, 0.2653],
        [0.1015, 0.0778, 0.0598, 0.6190]])

In [ ]:
# Check random tensor dims
random_tensor.ndim

2

In [ ]:
# Create random tensor with similar to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height width and color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and Ones

In [ ]:
# Create a tensor of all zeros

zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# cheking data type
print(zeros.dtype)
print(ones.dtype)
print(random_tensor.dtype)
print(random_image_size_tensor.dtype)

torch.float32
torch.float32
torch.float32
torch.float32


# Creating a range of tensors and tensors-like

In [ ]:
# Use torch range
one_to_ten = torch.arange(start=1,end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

tensors-like will create a tensor with any value but it's size will be same as another tensor

In [ ]:
# Creating tensor like

ten_zeroes = torch.zeros_like(one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what data type is the tensor (e.g. float32 or float16)
                               device=None, # CPU or GPU -> When It's a GPU, use word "CUDA"
                               requires_grad=False) # To pytorch to track the gradients 

float_32_tensor

tensor([3., 6., 9.])

Converting same float32 tensor to float16 tensor

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

# Getting information from Tensors

1. Get data type from a Tensor - `tensor.dtype`
2. Get shape from a Tensor - `tensor.shape`
3. Get device from a Tensor - `tensor.device`

In [ ]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2248, 0.7955, 0.4361, 0.5917],
        [0.8550, 0.1265, 0.0360, 0.4409],
        [0.9272, 0.7163, 0.9399, 0.5239]])

In [ ]:
# Find the details about the tensor
print(some_tensor)
print(f"\nData type of some_tensor: {some_tensor.dtype}")
print(f"Shape of some_tensor: {some_tensor.shape}")
print(f"Device type of some_tensor: {some_tensor.device}")

tensor([[0.2248, 0.7955, 0.4361, 0.5917],
        [0.8550, 0.1265, 0.0360, 0.4409],
        [0.9272, 0.7163, 0.9399, 0.5239]])

Data type of some_tensor: torch.float32
Shape of some_tensor: torch.Size([3, 4])
Device type of some_tensor: cpu


# Manipulating Tensors (Tensor operations)

1. Addition
2. Substraction
3. Multiplication (Element-wise)
4. Division
5. Matrix Multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Substract 10 from tensor
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built functions
print(torch.add(tensor,10))
print(torch.sub(tensor,10))
print(torch.mul(tensor,10))
print(torch.div(tensor,10))

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


## Matrix Multiplications

1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [ ]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equal {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equal tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.65 ms, sys: 0 ns, total: 2.65 ms
Wall time: 2.84 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 78 µs, sys: 0 ns, total: 78 µs
Wall time: 83.4 µs


tensor(14)

# Matrix multiplication rules

1. The inner dimensions must match:

- `(3,2) @ (3,2) - Won't work`
- `(2,3) @ (3,2) - Will work`
- `(3,2) @ (2,3) - Will work`

2. The resulting matrix has the shape of outer dimensions:

- `(2, 3) @ (3, 2) -> (2,2)`
- `(3, 2) @ (2, 3) -> (3,3)`

# One of the most common errors in deep learning: Shape error

In [ ]:
# shapes for matrix multiplication

tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

# torch.mm(tensor_A, tensor_B) # mm is short for matmul
# This gives the sahpe error becuse inner dimensions are not matching.

We can resolve above tensor shape issue by using **transpose** 

A **transpose** switches the axes of a given tensor.

`(3, 2) -> transpose -> (2,3)`

In [ ]:
# Checking the original tensor_B

tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
# tensor_B after transpose

tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
# Now we can multiply tensor_A and tensor_B

torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

# Finding the min, max, mean, sum and etc (tensor aggregation)

In [ ]:
# Creating a tensor

a = torch.arange(0,100,10)
a

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min

torch.min(a),  a.min() # a.min() do the same thing as the torch.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max

torch.max(a), a.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean

torch.mean(a.type(torch.float32)) # changing data type to float32, otherwise errors will pop-up

tensor(45.)

In [ ]:
# We can get the same results by doing the below operation

a.type(torch.float32).mean()

tensor(45.)

In [ ]:
# Find the sum

torch.sum(a)

tensor(450)

In [ ]:
# Find the sum with short wat

a.sum()

tensor(450)